<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Evaluating the Spread and Control of Zebra Mussels in U.S. Waterways</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>


<meta name="citation_title" content="Evaluating the Spread and Control of Zebra Mussels in U.S. Waterways">
<meta name="citation_author" content="Brittany Bobb">
<meta name="citation_author" content="Louisa Beckett">
<meta name="citation_author" content="Tayler Kordiak">
<meta name="citation_author" content="Austin Sharrah">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Benthic;,citation_author=undefined Merriam-Webster;,citation_fulltext_html_url=https://www.merriam-webster.com/dictionary/benthic;,citation_publisher=In &amp;amp;amp;lt;i&amp;gt;Merriam-Webster.com dictionary&amp;lt;/i&amp;gt;;">
<meta name="citation_reference" content="citation_title=Impacts of zebra mussels on aquatic communities and their role as ecosystem engineers;,citation_author=A. Y. Karatayev;,citation_author=L. E. Burlakova;,citation_author=D. K. Padilla;,citation_editor=E. Leppäkoski;,citation_editor=S. Gollasch;,citation_editor=S. Olenin;,citation_publication_date=2002;,citation_cover_date=2002;,citation_year=2002;,citation_fulltext_html_url=https://doi.org/10.1007/978-94-015-9956-6_43;,citation_doi=10.1007/978-94-015-9956-6_43;,citation_inbook_title=Invasive aquatic species of europe: Distribution, impacts, and management;">
<meta name="citation_reference" content="citation_title=Invasive zebra mussels;,citation_author=S. Knoch;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://www.nps.gov/articles/zebra-mussels.htm;">
<meta name="citation_reference" content="citation_title=Prevent the spread of mussels;,citation_author=California State Water Resources Control Board;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://water.ca.gov/News/Blog/2019/May-2019/Prevent-the-Spread-of-Mussels;">
<meta name="citation_reference" content="citation_title=What are zebra mussels and why should we care about them?;,citation_author=U. S. Geological Survey;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.usgs.gov/faqs/what-are-zebra-mussels-and-why-should-we-care-about-them;">
<meta name="citation_reference" content="citation_title=Copper treatment shows promise to control zebra mussel density in lakes;,citation_author=Minnesota Lakes &amp;amp;amp; Rivers Advocates;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_publisher=https://mnlakesandrivers.org/copper-treatment-shows-promise-to-control-zebra-mussel-density-in-lakes/;">
<meta name="citation_reference" content="citation_title=EarthTec&amp;amp;amp;lt;sup&amp;gt;&amp;lt;/sup&amp;gt; QZ;,citation_author=Univar Solutions;,citation_publisher=https://www.univarsolutions.com/product-categories/solvents/additional-solvents/earthtec-qz;">
<meta name="citation_reference" content="citation_title=Copper-based control: Zebra mussel settlement and non-target impacts data;,citation_author=J. A. Luoma;,citation_author=T. J. Severson;,citation_author=M. T. Barbour;,citation_author=J. K. Wise;,citation_publication_date=2020;,citation_cover_date=2020;,citation_year=2020;,citation_fulltext_html_url=https://doi.org/10.5066/P9B9NUQM;,citation_doi=10.5066/P9B9NUQM;,citation_publisher=USGS data release; U.S. Geological Survey;">
<meta name="citation_reference" content="citation_title=Copper kills fish, but not all copper is created equal - zebra mussel myth #4;,citation_author=B. Showalter;,citation_publication_date=2019;,citation_cover_date=2019;,citation_year=2019;,citation_fulltext_html_url=https://earthtecqz.com/zebra-mussels/zebra-mussel-myth-4-copper-kills-fish/;">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Evaluating the Spread and Control of Zebra Mussels in U.S. Waterways</h1>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Brittany Bobb </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Louisa Beckett </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Tayler Kordiak </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Austin Sharrah </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Colorado State
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></p></div><div class="quarto-title-meta-contents"><p><a href="index-meca.zip" data-meca-link="true"><i class="bi bi-archive"></i>MECA Bundle</a></p></div></div></div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="index-preview.html"><i class="bi bi-journal-code"></i>Article Notebook</a></li><li><a href="docs\index-preview.html"><i class="bi bi-journal-code"></i>Evaluating the Spread and Control of Zebra Mussels in U.S. Waterways</a></li></ul></div></div>
<main class="content quarto-banner-title-block" id="quarto-document-content">



  


<p><strong>Abstract</strong></p>
<p>Author : Louisa Beckett</p>
<p>Zebra mussels (Dreissena polymorpha) pose a significant threat to freshwater ecosystems. This study investigates the impact of low-dose copper treatment (EarthTec QZ) on zebra mussel mortality in two separate bays within Lake Minnetonka, Minnesota: the relatively isolated St.&nbsp;Albans Bay and the more open Robinson Bay. We hypothesized that St.&nbsp;Albans Bay would exhibit higher copper concentrations and greater zebra mussel mortality due to reduced water mixing compared to Robinson Bay. Using a publicly available USGS dataset spanning July to October 2019, we analyzed trends in zebra mussel density and copper concentrations across five buoys in each bay. Faceted time-series plots revealed a substantial reduction in zebra mussel populations in St.&nbsp;Albans Bay following a 10-day copper treatment period, whereas Robinson Bay maintained significantly higher mussel densities. A paired t-test comparing copper levels at selected buoys in both bays demonstrated statistically significant differences (p = 0.0401), supporting the notion that the open morphology of Robinson Bay led to lower and more variable copper concentrations. While water quality parameters: dissolved oxygen, pH, and temperature, remained relatively stable, slight downward trends in dissolved oxygen and pH were observed in St.&nbsp;Albans Bay during treatment. Our findings suggest that bay morphology plays an important role in the effectiveness of localized copper treatments for zebra mussel control. It also highlights the importance of considering site-specific characteristics for targeted management strategies.</p>
<p><strong>Introduction</strong></p>
<p>Author: Tayler Kordiak</p>
<p>Zebra mussels (Dreissena polymorpha) are an aggressive bivalve invasive species that dominate and alter the freshwater ecosystems they invade. This benthic species, meaning living on the bottom of a body of water <span class="citation" data-cites="merriamwebster_benthic">(<a href="#ref-merriamwebster_benthic" role="doc-biblioref">Merriam-Webster n.d.</a>)</span>, often affects trophic levels by destroying ecosystem processes <span class="citation" data-cites="karatayev2002impacts">(<a href="#ref-karatayev2002impacts" role="doc-biblioref">Karatayev, Burlakova, and Padilla 2002</a>)</span>. Some ecosystem processes that are affected include oxygen and nutrient availability, sedimentation rates, and increased water temperature which can lead to a reduction of native species, due to outcompeting, that are detrimental to the freshwater ecosystems they belong to. Along with affecting the lake species, it also causes human problems economically and recreationally. Zebra mussels coined the term “biofouling” meaning that they attach to any hard surface such as rocks, boats, and docks because of their byssal threads <span class="citation" data-cites="nps_zebramussels_2025">(<a href="#ref-nps_zebramussels_2025" role="doc-biblioref">Knoch 2021</a>)</span>. These mussels may not affect boats in the water for short trips, however, when these things are left in infested water for long periods, like power plant water intakes, it can cause millions of dollars in damage <span class="citation" data-cites="usgs_zebramussels_2025">(<a href="#ref-usgs_zebramussels_2025" role="doc-biblioref">Survey 2025</a>)</span>. Zebra mussels were first brought into the United States in the mid-1980s, and it is hypothesized that they were brought from a cargo ship that ported in the St.&nbsp;Claire River, which connects Lake Erie and Lake Huron. The cargo ship, coming from Europe, dumped its ballast water which in turn dumped the organisms from the freshwater ports in Russia and Ukraine that they are native to. They were first discovered in Lake St.&nbsp;Claire, and quickly spread to the St.&nbsp;Croix and Mississippi Rivers naturally, and further to the west through human transport on boats <span class="citation" data-cites="nps_zebramussels_2025">(<a href="#ref-nps_zebramussels_2025" role="doc-biblioref">Knoch 2021</a>)</span>. Currently, there are some preventative measures for halting the spread of infested waters to non-infested waters such as ensuring personal recreation equipment such as boats, jet skis, and trailers for these items are cleaned, drained, and well-dried before leaving the boat launch. During high-traffic months, there will typically be a USGS or State Department of Natural Resources monitor to inspect the boats that come in and out of the lakes to ensure that the proper safety measures are taken. This process includes inspecting equipment and removing any visible mussels, however, this may be difficult due to their small size, and draining live wells, bilges, and bait buckets of any water before departing. As an owner of this type of recreational equipment, it’s also your duty to ensure that your items are completely dry and washed before entering another body of water <span class="citation" data-cites="ca_water_mussels_2019">(<a href="#ref-ca_water_mussels_2019" role="doc-biblioref">Board 2019</a>)</span>.</p>
<p>Some current control methods are rapid response agencies, public education through signage and monitors at boat launches, as well as some physical, biological, and chemical controls. An example of a physical control measure is water drawdowns in canals and aqueducts which can dry and kill zebra mussels. There is ongoing biological research to determine the natural killers of zebra mussels, and the control measure that our group is interested in researching further is the chemical component that is being taken to kill off these mussels. The research question that we will be testing within the program R is, does the concentration of low-dose copper treatment in the treated St.&nbsp;Albans Bay in Lake Minnetonka in Minnesota affect zebra mussel mortality? We will be comparing this to an untreated Bay in the same lake, called Robinson Bay, and the data has been taken from the USGS website and initial low-dose copper treatment was applied in July of 2019, and ended in October of 2019. The work that we will be conducting is creating visual graphs for this experiment that was done in Lake Minnetonka. The objective was to maintain copper concentrations within St.&nbsp;Albans Bay to 60ug/L in the thermocline of the water for 10 days consecutively. Five testing sites were distinguished by buoys in each Bay. The goal was to target zebra mussel veligers (free-floating offspring) with the copper treatment called EarthTec QZ <span class="citation" data-cites="mnlra2019copper">(<a href="#ref-mnlra2019copper" role="doc-biblioref">Minnesota Lakes &amp; Rivers Advocates 2019</a>)</span>. This is non-toxic for non-targeted animals within and outside of the lakes <span class="citation" data-cites="univar_earthtec_qz">(<a href="#ref-univar_earthtec_qz" role="doc-biblioref">Univar Solutions n.d.</a>)</span>. The data that will be used comes from the USGS Science-based catalog, which is a trusted website and displays public natural resource information for Lake Minnetonka, specifically, EarthTec QZ concentrations and zebra mussel density as well as mortality. We wanted to pick this lake because the testing zones will experience the same climate, topography, and prevention measures on the lake that are contaminated with zebra mussels. As for the methods, we will be using a log regression, decision tree, or random forest which will help us view the success of EarthTec QZ in St.&nbsp;Albans Bay compared to the control, Robinson Bay. We’ll want to apply regression analysis to view the statistical relationship between the treatments and the observed changes in the mussel population. Additionally, temporal trends will be assessed to evaluate the long-term impact of the control interventions. We will start with our full data, and pull out a sample of the data to be our training set. With the training set, we will be able to create resamples such as 10-fold cross-validation to compare the different models listed above to see which model best fits our data. Ensuring that each model has a specified model and engine. Once ranked, we will be able to decide which model we will use to show the density and mortality of zebra mussels within both lakes in Lake Minnetonka.</p>
<p><strong>Research Question</strong></p>
<p>How does copper treatment concentration affect zebra mussel mortality rates in bays with differing physical characteristics, such as the relative isolation of St.&nbsp;Albans Bay compared to the more open Robinson Bay?</p>
<p><strong>Hypothesis</strong></p>
<p>We hypothesize that St.&nbsp;Albans Bay will exhibit higher copper concentrations and lower zebra mussel populations than Robinson Bay due to its relative isolation from the rest of the lake, whereas the larger mouth of Robinson Bay will result in lower copper concentrations and will maintain higher mussel populations likely due to higher rates of water mixing.</p>
<p><strong>Methods</strong></p>
<p>Author: Brittany Bobb, Austin Sharrah</p>
<p>Using datasets from the USGS Science Data Catalog (SDC) publication on copper-based zebra mussel control in Lake Minnetonka, we aim to To evaluate the effectiveness of copper-based treatments in controlling zebra mussel populations, we analyzed time series data from two bays in Lake Minnetonka: Robinson’s Bay and St.&nbsp;Albans Bay. The specific datasets we utilized are the Copper treatment data, Zebra Mussel Settlement data, and the Water Chemistry data. These datasets effectively cover the treatment type, specific bays, copper concentration (EarthTec QZ), replication, time, date, and the water chemistry(dissolved oxygen, pH, and temperature) recorded at five buoy stations in each bay over a 10-day treatment period from July 21 to July 31 <span class="citation" data-cites="luoma2020copper">(<a href="#ref-luoma2020copper" role="doc-biblioref">Luoma et al. 2020</a>)</span>. While the data is largely structured, it did require cleaning such as handling duplicates, standardizing formatting, and addressing missing values. In this experiment, the copper concentrations were measured using two complementary analytical methods depending on sampling context and sensitivity requirements. Inductively Coupled Plasma (ICP) Spectroscopy was employed for its high sensitivity and accuracy in detecting trace metal concentrations in water samples <span class="citation" data-cites="luoma2020copper">(<a href="#ref-luoma2020copper" role="doc-biblioref">Luoma et al. 2020</a>)</span>. Additionally, the Hach porphyrin method was used as a rapid field-based test to monitor biologically available copper concentrations during the treatment period <span class="citation" data-cites="luoma2020copper">(<a href="#ref-luoma2020copper" role="doc-biblioref">Luoma et al. 2020</a>)</span>. The Hach method uses a colorimetric assay based on copper complexation with porphyrin reagents and is suited for routine monitoring of free copper ions <span class="citation" data-cites="luoma2020copper">(<a href="#ref-luoma2020copper" role="doc-biblioref">Luoma et al. 2020</a>)</span>. Both methods helped characterize spatial and temporal variability in copper exposure, particularly between Robinson’s Bay and St.&nbsp;Albans Bay, where differing hydrodynamic conditions may influence treatment distribution and retention <span class="citation" data-cites="luoma2020copper">(<a href="#ref-luoma2020copper" role="doc-biblioref">Luoma et al. 2020</a>)</span>. Total zebra mussel counts were collected at each buoy before and after the copper treatment period. Faceted time series plots were created to visualize changes in mussel abundance over time between bays and among buoy sites. Water quality parameters including dissolved oxygen (mg/L), pH, and temperature (°C) were also recorded at each site throughout the experiment to assess potential environmental side effects of the copper treatment and to examine whether these factors influenced treatment efficacy. To assess statistical differences in copper concentrations between bays, we conducted a paired t-test comparing copper levels at Buoy 4 and Buoy 5 in both Robinson’s and St.&nbsp;Albans Bay. These sites were selected for their representative positions and consistent data records. The t-test was used to determine whether observed differences in copper exposure were statistically significant.</p>
<p><strong>Results</strong></p>
<p>Author: Tayler Kordiak</p>
<p>After making a faceted time series plot with Total (mussel) Count vs.&nbsp;Date (Figure 1) we can see that Robinson’s Bay (Figure 1, left) had significantly more zebra mussels than St.&nbsp;Albans Bay (Figure 1, right). However, the treatment in St.&nbsp;Albans Bay did a better job at almost eliminating the mussels completely from the Bay. Post-exposure, Robinson’s Buoy numbers 1, 3, and 5 all still had between 350,000 and 380,000 mussels, while St.&nbsp;Albans Buoys post-exposure had almost 0-200 mussels. Our hypothesis states, we believe St.&nbsp;Albans Bay copper treatment will be more effective because the bay’s opening to the rest of the lake is much smaller than that of Robinson’s Bay, thus assuming that St.&nbsp;Albans will have a lower zebra mussel distribution post-treatment. In that same note, we ran another faceted time series plot, Copper Levels vs.&nbsp;Date (Figure 2). We wanted to see whether or not the amount of the EarthTec QZ differed from bay to bay. As shown in Figure 2, there are obvious differences in the levels, Robinson’s Bay (Figure 2, left) had varying levels of copper surrounding each testing site between 2-23 μg/L with an outlier on August 1st which we can disregard, and St.&nbsp;Albans Bay (Figure 2, right) had copper levels between 57-125 μg/L. These levels were pretty consistent during the 10 experimental days of July 21st and July 31st, but it is clear that St.&nbsp;Albans Bay had higher levels of the copper treatment, and our assumption from that is because of the openness of Robinson’s Bay compared to St.&nbsp;Albans Bay. The more mixing of untreated water with the treated water leads to a decrease in effectiveness.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
<a class="quarto-notebook-link" id="nblink-1" href="index-preview.html">Source: Article Notebook</a></div>
<p><em>Figure 1. Faceted Time-Series Graphs of Robinson’s Bay (left) and St.&nbsp;Albans Bay (right) with Total Count on the y-axis and Date on the x-axis, split by Buoy</em></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2"><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 2. Faceted Time-Series Graphs of Robinson’s Bay (left) and St.&nbsp;Albans Bay (right) with Copper levels (μg/L) on the y-axis and Date on the x-axis, split by Buoy</em></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  paired_data4$B4 and paired_data4$B5
t = 2.137, df = 33, p-value = 0.0401
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.2105335 8.5716541
sample estimates:
mean difference 
       4.391094 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/unnamed-chunk-16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="index_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></a></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 3. Faceted Time-Series Graphs showing Robinson’s Bay (left) St.&nbsp;Albans Bay (right) with Date on the x-axis and Dissolved Oxygen (mg/L) (top, left and right), pH (middle, left and right), and Temperature (℃) (bottom, left and right) on the y-axis</em></p>
<p>We realize that we have simply compared the two bays thus far using faceted time-series graphs, so we wanted to run a paired t-test, which could tell us if there is significance between the two bays. We decided to run the test on copper levels of Buoy 4 and Buoy 5 in both Robinson’s and St.&nbsp;Albans Bay to showcase statistical significance. After running the test, we got a p-value of 0.0401 and a t-value of 2.137 which is great and shows statistical significance (Table 1). There was clearly a difference between copper levels between bays, and more specifically between Buoy 4 and 5. Thus, we can reject the null hypothesis of there not being a difference in copper level between Robinson’s Bay and St.&nbsp;Albans Bay, and say with confidence that the openness to Lake Minnetonka of Robinson’s Bay can explain the lesser amount of copper at the five testing sites. Additionally, proving that the effectiveness of the copper treatment was more successful at the testing sites in St.&nbsp;Albans Bay. The copper treatment halted once the 10 days were up, this can be seen in Figure 2, and the levels of the copper started to decrease in both bays. This is a good thing because there is research out there that attests that extended use of EarthTec QZ can cause damage to the lake and aquatic life that reside there. This is because EarthTec QZ is copper in the form of biologically available copper, copper sulfate pentahydrate, which is acidic, thus turning the lake more acidic, or through killing algae, which will in turn consume the available oxygen within the lake <span class="citation" data-cites="showalter2019copper">(<a href="#ref-showalter2019copper" role="doc-biblioref">Showalter 2019</a>)</span>. This is why we wanted to add supplemental data that was in the data we obtained from the original experiment, as exhibited by Figure 3. In Figure 3, again, we have another faceted time-series graph which contains the Robinson’s Bay (Figure 3, left) and St.&nbsp;Albans Bay (Figure 3, right) with graphs depicting Dissolved Oxygen (mg/L) (Figure 3, top left, top right), pH (Figure 3, middle left, middle right) and Temperature (℃) (Figure 3, bottom left, bottom right) for both bays. We felt it was necessary to add this supplemental data in our report because we wanted to see if the copper treatment would have an effect on the Dissolved Oxygen, pH, or Temperature of the water, or the other way around. We hypothesized that these three factors could have been confounding variables that may have affected the ability for the copper treatment to do its job. From Figure 3, we can see that their Dissolved Oxygen, pH, and Temperature were not affected and did not seem to make a difference on the copper level or the effectiveness of the treatment itself. However, in St.&nbsp;Albans Bay, Dissolved Oxygen (Figure 3, right, top) and pH (Figure 3, right, middle) did have a downward trend during the time of the experiment. As for Robinson’s Bay, both Dissolved Oxygen (Figure 3, left, top) and pH (Figure 3, left, middle) had pretty steady levels, averaging about the same throughout the experiment days. This can be explained by the higher levels of copper within St.&nbsp;Albans Bay from Figure 2. Temperature did not seem to be affected by the copper treatment or vice versa during the experiment.</p>
<p><strong>Discussion &amp; Conclusion</strong></p>
<p>Author: Lousia Beckett</p>
<p>This study supports the hypothesis that bay morphology significantly influences the effectiveness of copper-based zebra mussel treatments. St.&nbsp;Albans Bay, which has a narrower connection to the rest of Lake Minnetonka, retained higher and more stable concentrations of EarthTec QZ, leading to a near-total reduction in zebra mussel populations across all five testing buoys. In contrast, Robinson’s Bay, with its wider mouth and greater rate of water exchange and mixing, maintained lower and more variable copper levels, resulting in substantially higher mussel densities post-treatment. This difference in treatment effectiveness is particularly visible after September 1st, when zebra mussel counts dropped sharply in St.&nbsp;Albans Bay whereas in Robinson’s Bay, the decrease was more gradual and had much less total change. The statistical significance observed in the paired t-test between Buoys 4 and 5 in both bays (p = 0.0401) reinforces the conclusion that bay openness affects mussel mortality. The more open Robinson’s Bay likely experienced increased mixing with untreated water from the main lake, diluting copper concentrations and reducing treatment effectiveness. This finding directly supports our hypothesis and emphasizes how geographic and hydrologic context plays a vital role in the success of aquatic invasive species interventions. Copper treatments don’t kill instantly; rather, they weaken zebra mussels over time, with mortality increasing as exposure lengthens. This is why copper application occurred in August while final population counts were recorded in September, to capture delayed treatment effects (Figures 1 &amp; 2). The data also suggest that copper has a delayed effect, with zebra mussel mortality increasing over time as exposure accumulates. This relationship underscores the importance of maintaining effective treatment concentrations over a sustained period, in this case, the 10-day treatment window, to maximize impact on zebra mussel larvae and newly settled individuals. While these findings are promising, there are limitations to our analysis. Both bays are connected to Lake Minnetonka, which introduces several potential confounding variables including water flow, organism dispersal, and external nutrients from runoff and such. Although St.&nbsp;Albans and Robinson’s Bays differ in their degree of isolation, both are influenced to some extent by lake-wide processes. This complicates our efforts to attribute population changes solely to treatment application. Environmental variables such as dissolved oxygen, pH, and temperature remained mostly stable during the study (Figure 3), but subtle downward trends in dissolved oxygen and pH in St.&nbsp;Albans Bay suggest potential interactions between copper exposure and aquatic chemistry that demand further investigation. Despite these challenges, our results have broader relevance for environmental data science and invasive species management. They highlight the importance of controlled experimental design, careful site selection, and accounting for spatial variability when interpreting treatment outcomes. Replicating this study across different geographic settings and expanding the survey window beyond three months would help validate the effectiveness and ecological safety of EarthTec QZ in diverse aquatic systems. This study provides evidence that low-dose copper treatments can be an effective, environmentally mindful method for zebra mussel control, especially when deployed in geographically favorable conditions such as partially closed off bays. These findings could inform predictive models used by lake managers to prioritize treatment sites based on bay geography and water exchange rates. Future work should continue to integrate spatial analysis, environmental monitoring, and advanced modeling techniques to optimize treatment strategies and reduce the ecological and economic impacts of invasive mussel populations.</p>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ca_water_mussels_2019" class="csl-entry" role="listitem">
Board, California State Water Resources Control. 2019. <span>“Prevent the Spread of Mussels.”</span> <a href="https://water.ca.gov/News/Blog/2019/May-2019/Prevent-the-Spread-of-Mussels">https://water.ca.gov/News/Blog/2019/May-2019/Prevent-the-Spread-of-Mussels</a>.
</div>
<div id="ref-karatayev2002impacts" class="csl-entry" role="listitem">
Karatayev, A. Y., L. E. Burlakova, and D. K. Padilla. 2002. <span>“Impacts of Zebra Mussels on Aquatic Communities and Their Role as Ecosystem Engineers.”</span> In <em>Invasive Aquatic Species of Europe: Distribution, Impacts, and Management</em>, edited by E. Leppäkoski, S. Gollasch, and S. Olenin. Dordrecht: Springer. <a href="https://doi.org/10.1007/978-94-015-9956-6_43">https://doi.org/10.1007/978-94-015-9956-6_43</a>.
</div>
<div id="ref-nps_zebramussels_2025" class="csl-entry" role="listitem">
Knoch, S. 2021. <span>“Invasive Zebra Mussels.”</span> <a href="https://www.nps.gov/articles/zebra-mussels.htm">https://www.nps.gov/articles/zebra-mussels.htm</a>.
</div>
<div id="ref-luoma2020copper" class="csl-entry" role="listitem">
Luoma, J. A., T. J. Severson, M. T. Barbour, and J. K. Wise. 2020. <span>“Copper-Based Control: Zebra Mussel Settlement and Non-Target Impacts Data.”</span> USGS data release; U.S. Geological Survey. <a href="https://doi.org/10.5066/P9B9NUQM">https://doi.org/10.5066/P9B9NUQM</a>.
</div>
<div id="ref-merriamwebster_benthic" class="csl-entry" role="listitem">
Merriam-Webster. n.d. <span>“Benthic.”</span> In <em>Merriam-Webster.com dictionary</em>. <a href="https://www.merriam-webster.com/dictionary/benthic">https://www.merriam-webster.com/dictionary/benthic</a>.
</div>
<div id="ref-mnlra2019copper" class="csl-entry" role="listitem">
Minnesota Lakes &amp; Rivers Advocates. 2019. <span>“Copper Treatment Shows Promise to Control Zebra Mussel Density in Lakes.”</span> <a href="https://mnlakesandrivers.org/copper-treatment-shows-promise-to-control-zebra-mussel-density-in-lakes/" class="uri">https://mnlakesandrivers.org/copper-treatment-shows-promise-to-control-zebra-mussel-density-in-lakes/</a>.
</div>
<div id="ref-showalter2019copper" class="csl-entry" role="listitem">
Showalter, B. 2019. <span>“Copper Kills Fish, but Not All Copper Is Created Equal - Zebra Mussel Myth #4.”</span> 2019. <a href="https://earthtecqz.com/zebra-mussels/zebra-mussel-myth-4-copper-kills-fish/">https://earthtecqz.com/zebra-mussels/zebra-mussel-myth-4-copper-kills-fish/</a>.
</div>
<div id="ref-usgs_zebramussels_2025" class="csl-entry" role="listitem">
Survey, U. S. Geological. 2025. <span>“What Are Zebra Mussels and Why Should We Care about Them?”</span> <a href="https://www.usgs.gov/faqs/what-are-zebra-mussels-and-why-should-we-care-about-them">https://www.usgs.gov/faqs/what-are-zebra-mussels-and-why-should-we-care-about-them</a>.
</div>
<div id="ref-univar_earthtec_qz" class="csl-entry" role="listitem">
Univar Solutions. n.d. <span>“EarthTec<sup></sup> QZ.”</span> <a href="https://www.univarsolutions.com/product-categories/solvents/additional-solvents/earthtec-qz" class="uri">https://www.univarsolutions.com/product-categories/solvents/additional-solvents/earthtec-qz</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"descPosition":"bottom","openEffect":"zoom","closeEffect":"zoom","loop":false,"selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>